### ISSUE TITLE
Possible memory overflow?

### ISSUE THREAD

**Issue by th-otto** [mikrosk/led_blur#1]
I've added back the possibility to use SDL again, so i can compile it on linux. That seems to work, except when i use -s to scale the window up. That crashes with 
```
corrupted size vs. prev_size
Aborted (core dumped)
```
(i think this message is from glibc).

Running it under valgrind, i get:
```
==11033== Invalid write of size 8
==11033==    at 0x40C608: GP32toPC (gp32_functions.c:198)
==11033==    by 0x40C697: GpSurfaceFlip (gp32_functions.c:217)
==11033==    by 0x40CFC7: update_precbar (precalcs.c:187)
==11033==    by 0x40ED70: PlasmaInit (precalcs.c:443)
==11033==    by 0x40EF33: precalcs (precalcs.c:506)
==11033==    by 0x40C8A0: Init (ledblur.c:77)
==11033==    by 0x40CA66: main (ledblur.c:135)
==11033==  Address 0xa89c420 is 0 bytes after a block of size 614,400 alloc'd
==11033==    at 0x484874F: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==11033==    by 0x5120CA3: ??? (in /usr/lib64/libSDL2-2.0.so.0.2800.3)
==11033==    by 0x488F11D: SDL_SetVideoMode (in /usr/lib64/libSDL-1.2.so.1.2.64)
==11033==    by 0x40C3FF: GpGraphicModeSet (gp32_functions.c:114)
==11033==    by 0x40C82F: InitGraphics (ledblur.c:54)
==11033==    by 0x40C869: Init (ledblur.c:70)
==11033==    by 0x40CA66: main (ledblur.c:135)
```

It crashes shortly after.

Changing the unsigned long at https://github.com/mikrosk/led_blur/blob/02723ac4f89978a0d52b00fce4ae536fb8125b22/source/gp32_functions.c#L186 to uint32_t seems to fix that.

**Comment by mikrosk** [comment]
Oofff.... I guess you're compiling it as x64 binary? I don't think it was ready for this kind of upgrade, it's amazing that this is all it takes to make it executable on 64-bit Linux.

**Comment by th-otto** [comment]
Yes, 64bit of course.

And as said you need to add back in SDL support for playing music again before it works on linux. If you want i can send you a diff, but i only needed that for testing.
